# Generated by Django 2.2.13 on 2020-07-17 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('hour', models.IntegerField(choices=[(0, '10'), (1, '11'), (2, '12'), (3, '13'), (4, '14'), (5, '15'), (6, '16'), (7, '17'), (8, '18'), (9, '19')])),
                ('start_slot', models.IntegerField(choices=[(0, '00'), (1, '15'), (2, '30'), (3, '45')])),
                ('duration', models.IntegerField(choices=[(0, '1'), (0, '2'), (0, '3'), (0, '4')])),
                ('instructor', models.BooleanField()),
                ('gear', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
